TF.WeiXinVote/Controllers/AdminController.cs
namespace TF.Controllers
{
    using SoMain.Common;
    using System;
    using System.Collections.Generic;
    using System.Runtime.InteropServices;
    using System.Web.Mvc;
    using TF;
    using TF.WeiXinVote.Data;

    public class AdminController : BaseController
    {
        [User]
        public ActionResult BonusRecord(long page = 1L, string mobile = "")
        {
            Page<VoteBonusRecord> model = SqlFactory.GetSqlhelper().CreateWhere<VoteBonusRecord>().IfTrueWhere(mobile != "", o => o.Mobile == mobile).OrderBy<DateTime>(o => o.CreateTime, AscDesc.Desc).Page(page, 20L);
            return base.View(model);
        }

        [User]
        public ActionResult Index()
        {
            object obj1 = base.Session["user"];
            return base.View();
        }

        public ActionResult Login()
        {
            string str;
            string str2;
            string str3;
            Rsa.CreateKey(out str, out str2, out str3);
            base.ViewData["n"] = str2;
            base.ViewData["e"] = str3;
            base.Session["key"] = str;
            base.ClearCookie("c");
            base.ClearCookie("v");
            base.ClearCookie("m");
            return base.View();
        }

        [HttpPost]
        public ActionResult Login(string user, string pwd, bool rm)
        {
            user = Rsa.Decrypt(base.Session["key"].ToString(), user);
            pwd = Rsa.Decrypt(base.Session["key"].ToString(), pwd);
            pwd = Md5.GetMd5String(pwd);
            DbUser user2 = base.helper.CreateWhere<DbUser>().Where(q => q.Enable).Where(q => q.UserName == user).Where(q => q.PassWord == pwd).FirstOrDefault();
            if (user2 == null)
            {
                return base.Error("用户名或密码错误！");
            }
            base.Session["user"] = user2;
            return base.Success();
        }

        [User]
        public ActionResult Questions()
        {
            DbUser user = base.Session["user"] as DbUser;
            List<VoteQuestions> model = SqlFactory.GetSqlhelper().CreateWhere<VoteQuestions>().Where(o => o.VoteID == user.LimitVoteID).Select();
            return base.View(model);
        }

        [User]
        public ActionResult VoteBonus()
        {
            DbUser user = base.Session["user"] as DbUser;
            List<TF.WeiXinVote.Data.VoteBonus> model = SqlFactory.GetSqlhelper().CreateWhere<TF.WeiXinVote.Data.VoteBonus>().Where(o => o.VoteID == user.LimitVoteID).Select();
            return base.View(model);
        }

        [User]
        public ActionResult VoteBonusAdd() {return base.View();} 
            

        [User, HttpPost, ValidateInput(false)]
        public ActionResult VoteBonusAdd(TF.WeiXinVote.Data.VoteBonus bonus)
        {
            DbUser user = base.Session["user"] as DbUser;
            bonus.VoteID = user.LimitVoteID;
            SqlFactory.GetSqlhelper().Save<TF.WeiXinVote.Data.VoteBonus>(bonus);
            return base.Success();
        }

        [User]
        public ActionResult VoteBonusDel(int id)
        {
            SqlFactory.GetSqlhelper().DeleteById<TF.WeiXinVote.Data.VoteBonus>(id);
            return base.Success();
        }

        [User]
        public ActionResult VoteBonusEdit(int id)
        {
            TF.WeiXinVote.Data.VoteBonus model = SqlFactory.GetSqlhelper().SingleById<TF.WeiXinVote.Data.VoteBonus>(id);
            return base.View(model);
        }

        [HttpPost, ValidateInput(false), User]
        public ActionResult VoteBonusEdit(TF.WeiXinVote.Data.VoteBonus bonus)
        {
            SqlFactory.GetSqlhelper().Save<TF.WeiXinVote.Data.VoteBonus>(bonus);
            return base.Success();
        }

        [User]
        public ActionResult VotePerson()
        {
            DbUser user = base.Session["user"] as DbUser;
            List<VotePersons> model = SqlFactory.GetSqlhelper().CreateWhere<VotePersons>().Where(o => o.VoteID == user.LimitVoteID).OrderBy<int>(o => o.NO, AscDesc.Asc).Select();
            return base.View(model);
        }

        [User]
        public ActionResult VotePersonAdd() { return base.View(); }
            

        [User, ValidateInput(false), HttpPost]
        public ActionResult VotePersonAdd(VotePersons person)
        {
            DbUser user = base.Session["user"] as DbUser;
            person.VoteID = user.LimitVoteID;
            if (string.IsNullOrEmpty(person.RealName))
            {
                return base.Error("请输入姓名");
            }
            SqlFactory.GetSqlhelper().Save<VotePersons>(person);
            return base.Success();
        }

        [User]
        public ActionResult VotePersonDel(int id)
        {
            SqlFactory.GetSqlhelper().DeleteById<VotePersons>(id);
            return base.Success();
        }

        [User]
        public ActionResult VotePersonEdit(int id)
        {
            VotePersons model = SqlFactory.GetSqlhelper().SingleById<VotePersons>(id);
            return base.View(model);
        }

        [User]
        public ActionResult VoteQuestionAdd()
        {
            DbUser user = base.Session["user"] as DbUser;
            List<VotePersons> list = SqlFactory.GetSqlhelper().CreateWhere<VotePersons>().Where(o => o.VoteID == user.LimitVoteID).Select();
            base.ViewData["persons"] = list;
            return base.View();
        }

        [HttpPost, ValidateInput(false), User]
        public ActionResult VoteQuestionAdd(VoteQuestions question)
        {
            DbUser user = base.Session["user"] as DbUser;
            question.VoteID = user.LimitVoteID;
            if (string.IsNullOrEmpty(question.Person))
            {
                return base.Error("请选择关联人员");
            }
            SqlFactory.GetSqlhelper().Save<VoteQuestions>(question);
            return base.Success();
        }

        [User]
        public ActionResult VoteQuestionDel(int id)
        {
            SqlFactory.GetSqlhelper().DeleteById<VoteQuestions>(id);
            return base.Success();
        }

        [User]
        public ActionResult VoteQuestionEdit(int id)
        {
            VoteQuestions model = SqlFactory.GetSqlhelper().SingleById<VoteQuestions>(id);
            DbUser user = base.Session["user"] as DbUser;
            List<VotePersons> list = SqlFactory.GetSqlhelper().CreateWhere<VotePersons>().Where(o => o.VoteID == user.LimitVoteID).Select();
            base.ViewData["persons"] = list;
            return base.View(model);
        }

        #region 页面
        [User]
        public ActionResult VotePage()
        {
            DbUser user = base.Session["user"] as DbUser;
            List<VotePages> model = SqlFactory.GetSqlhelper().CreateWhere<VotePages>().Where(o => o.VoteID == user.LimitVoteID).OrderBy(o => o.ID, AscDesc.Desc).Select();
            return base.View(model);
        }

        [User]
        public ActionResult VotePageAdd() { return base.View(); }


        [User, ValidateInput(false), HttpPost]
        public ActionResult VotePageAdd(VotePages page)
        {
            DbUser user = base.Session["user"] as DbUser;
            page.VoteID = user.LimitVoteID;
            SqlFactory.GetSqlhelper().Save<VotePages>(page);
            return base.Success();
        }

        [User]
        public ActionResult VotePageDel(int id)
        {
            SqlFactory.GetSqlhelper().DeleteById<VotePages>(id);
            return base.Success();
        }

        [User]
        public ActionResult VotePageEdit(int id)
        {
            VotePages model = SqlFactory.GetSqlhelper().SingleById<VotePages>(id);
            return base.View(model);
        }
        #endregion
    }
}

TF.WeiXinVote/Controllers/AdminLTEController.cs
namespace TF.Controllers
{
    using System;
    using System.Web.Mvc;

    public class AdminLTEController : Controller
    {
        public ActionResult _Footer(){

            return   base.PartialView();
        }
        public ActionResult _Header() {

            return   base.PartialView();
        }
        public ActionResult _HeaderUserInfo() {

            return   base.PartialView();
        }
        public ActionResult _MenuPath(object menuPath)
        {
            base.TempData["_MenuPath"] = menuPath;
            return base.PartialView();
        }

        public ActionResult _Sidebar() {

            return   base.PartialView();
        }
        public ActionResult _SidebarControl() {

            return   base.PartialView();
        }

        public ActionResult _SidebarMenu()
        {

            return base.PartialView();
        }
    }
}

TF.WeiXinVote/Views/AdminLTE/_Footer.cshtml
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> 1.00
    </div>
    <strong>Copyright &copy; 2017 .</strong> All rights reserved.
</footer>

TF.WeiXinVote/Views/AdminLTE/_Header.cshtml
@{
    Layout = null;
    

}
<header class="main-header">
    <a class="logo">
        <span class="logo-mini"><b>投票</b></span>
        <span class="logo-lg"><b>投票</b>管理系统</span>
    </a>
    <nav class="navbar navbar-static-top" role="navigation">
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">侧边栏切换按钮</span>
        </a>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">


                <li class="dropdown user user-menu">
                    @{Html.RenderAction("_HeaderUserInfo");}
                </li>
                <li>
                    <a href="@Url.Action("Login", "Admin")">
                        <i class="fa fa-sign-out"></i>
                        &nbsp;注销
                    </a>
                </li>
            </ul>
        </div>
    </nav>
</header>

TF.WeiXinVote/Views/AdminLTE/_HeaderUserInfo.cshtml
@{
    var user = Session["user"] as TF.WeiXinVote.Data.DbUser;
}
<a href="#" class="dropdown-toggle" data-toggle="dropdown">
    <img src="" class="user-image" />
    <span class="hidden-xs">@user.UserName</span>
</a>
<ul class="dropdown-menu">
    <!-- User image -->
    <li class="user-header">
        <img src="" class="img-circle" alt="User Image" />
        <p>
            name
            <small>name</small>
        </p>
    </li>
    <!-- Menu Body -->
    <li class="user-body">
        <div class="col-xs-4 text-center">
            <a href="#">Followers</a>
        </div>
        <div class="col-xs-4 text-center">
            <a href="#">Sales</a>
        </div>
        <div class="col-xs-4 text-center">
            <a href="#">Friends</a>
        </div>
    </li>
    <!-- Menu Footer-->
    <li class="user-footer">
        @*<div class="pull-left">
                <a href="#" class="btn btn-default btn-flat">Profile</a>
            </div>*@
        <div class="pull-right">
            <a href="@Url.Action("Login", "Admin")" class="btn btn-default btn-flat">注销</a>
        </div>
    </li>
</ul>

TF.WeiXinVote/Views/AdminLTE/_Sidebar.cshtml
<aside class="main-sidebar">
    <section class="sidebar">
        @*<div class="user-panel">
            <div class="pull-left image">
                <img src="" class="img-circle" />
            </div>
            <div class="pull-left info">
                <p>name</p>
                <a href="#"><i class="fa fa-circle text-success"></i> 在线</a>
            </div>
        </div>*@
        @{Html.RenderAction("_SidebarMenu", "AdminLTE");}
    </section>
</aside>

TF.WeiXinVote/Views/AdminLTE/_SidebarMenu.cshtml
@{
    var user = Session["user"] as TF.WeiXinVote.Data.DbUser;
}
<ul class="sidebar-menu">
        <li class="header">投票管理</li>  
        @*<li>
            <a href="pages/widgets.html">
                <i class="fa fa-th"></i> <span>Widgets</span>
                <span class="pull-right-container">
                    <small class="label pull-right bg-green">new</small>
                </span>
            </a>
        </li>*@
        <li><a href="@Url.Action("VotePerson","Admin")"><i class="fa fa-book"></i> <span>被投票人信息</span></a></li>
        <li><a href="@Url.Action("Questions","Admin")"><i class="fa fa-book"></i> <span>问答管理</span></a></li>
        <li><a href="@Url.Action("VoteBonus","Admin")"><i class="fa fa-book"></i> <span>奖品管理</span></a></li>
        <li><a href="@Url.Action("BonusRecord","Admin")"><i class="fa fa-book"></i> <span>中奖信息</span></a></li>
        <li><a href="@Url.Action("VotePage","Admin")"><i class="fa fa-book"></i> <span>页面管理</span></a></li>
</ul>