TF.WeiXinVote/Controllers/AdminLTEController.cs
namespace TF.Controllers
{
    using System;
    using System.Web.Mvc;

    public class AdminLTEController : Controller
    {
        public ActionResult _Footer(){

            return   base.PartialView();
        }
        public ActionResult _Header() {

            return   base.PartialView();
        }
        public ActionResult _HeaderUserInfo() {

            return   base.PartialView();
        }
        public ActionResult _MenuPath(object menuPath)
        {
            base.TempData["_MenuPath"] = menuPath;
            return base.PartialView();
        }

        public ActionResult _Sidebar() {

            return   base.PartialView();
        }
        public ActionResult _SidebarControl() {

            return   base.PartialView();
        }

        public ActionResult _SidebarMenu()
        {

            return base.PartialView();
        }
    }
}

TF.WeiXinVote/Controllers/MenuController.cs
namespace Senparc.Weixin.MP.Sample.Controllers
{
    using Senparc.Weixin.Entities;
    using Senparc.Weixin.Exceptions;
    using Senparc.Weixin.MP;
    using Senparc.Weixin.MP.CommonAPIs;
    using Senparc.Weixin.MP.Entities;
    using Senparc.Weixin.MP.Entities.Menu;
    using System;
    using System.Web.Mvc;

    public class MenuController : Controller
    {
        [HttpPost]
        public ActionResult CreateMenu(string token, GetMenuResultFull resultFull, MenuMatchRule menuMatchRule)
        {
            bool flag = (menuMatchRule != null) && !menuMatchRule.CheckAllNull();
            string str = "使用接口："+ (flag ? "个性化菜单接口" : "普通自定义菜单接口")+"。";
            try
            {
                WxJsonResult result = null;
                IButtonGroupBase buttonData = null;
                if (flag)
                {
                    ConditionalButtonGroup menu = CommonApi.GetMenuFromJsonResult(resultFull, new ConditionalButtonGroup()).menu as ConditionalButtonGroup;
                    menu.matchrule = menuMatchRule;
                    result = CommonApi.CreateMenuConditional(token, menu, 0x2710);
                    str = str + "menuid："+(result as CreateMenuConditionalResult).menuid+"。";
                }
                else
                {
                    buttonData = CommonApi.GetMenuFromJsonResult(resultFull, new ButtonGroup()).menu;
                    result = CommonApi.CreateMenu(token, buttonData, 0x2710);
                }
                var data = new {
                    Success = result.errmsg == "ok",
                    Message = "菜单更新成功。" + str
                };
                return base.Json(data);
            }
            catch (Exception exception)
            {
                var type2 = new {
                    Success = false,
                    Message = "更新失败："+exception.Message+"。"+str
                };
                return base.Json(type2);
            }
        }

        public ActionResult DeleteMenu(string token)
        {
            try
            {
                WxJsonResult result = CommonApi.DeleteMenu(token);
                var data = new {
                    Success = result.errmsg == "ok",
                    Message = result.errmsg
                };
                return base.Json(data, JsonRequestBehavior.AllowGet);
            }
            catch (Exception exception)
            {
                var type2 = new {
                    Success = false,
                    Message = exception.Message
                };
                return base.Json(type2, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult GetMenu(string token)
        {
            try
            {
                GetMenuResult menu = CommonApi.GetMenu(token);
                if (menu == null)
                {
                    return base.Json(new { error = "菜单不存在或验证失败！" }, JsonRequestBehavior.AllowGet);
                }
                return base.Json(menu, JsonRequestBehavior.AllowGet);
            }
            catch (WeixinMenuException exception)
            {
                return base.Json(new { error = "菜单不存在或验证失败：" + exception.Message }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception exception2)
            {
                return base.Json(new { error = "菜单不存在或验证失败：" + exception2.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult GetToken(string appId, string appSecret)
        {
            try
            {
                AccessTokenResult data = CommonApi.GetToken(appId, appSecret, "client_credential");
                return base.Json(data, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                return base.Json(new { error = "执行过程发生错误！" }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Index()
        {
            GetMenuResult model = new GetMenuResult(new ButtonGroup());
            for (int i = 0; i < 3; i++)
            {
                SubButton button = new SubButton();
                for (int j = 0; j < 5; j++)
                {
                    SingleClickButton item = new SingleClickButton();
                    button.sub_button.Add(item);
                }
            }
            return base.View(model);
        }
    }
}

TF.WeiXinVote/Views/Shared/_AdminLTE.cshtml
@{
    
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewBag.Title</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.6 -->
    <link rel="stylesheet" href="/bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/plugins/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="/plugins/ionicons/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="/dist/css/skins/_all-skins.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="/plugins/iCheck/flat/blue.css">
    <!-- Morris chart -->
    <link rel="stylesheet" href="/plugins/morris/morris.css">
    <!-- jvectormap -->
    <link rel="stylesheet" href="/plugins/jvectormap/jquery-jvectormap-1.2.2.css">
    <!-- Date Picker -->
    <link rel="stylesheet" href="/plugins/datepicker/datepicker3.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="/plugins/daterangepicker/daterangepicker.css">
    <!-- bootstrap wysihtml5 - text editor -->
    <link rel="stylesheet" href="/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        @{Html.RenderAction("_Header", "AdminLTE");}
        @{Html.RenderAction("_Sidebar", "AdminLTE");}
        <div class="content-wrapper">
            <section class="content-header">
                @*@{Html.RenderAction("_MenuPath", "AdminLTE", new { menuPath = TempData["MenuPath"] });}*@
            </section>
            <section class="content">
                @RenderBody()
            </section>
        </div>
        @{Html.RenderAction("_Footer", "AdminLTE");}
        @{Html.RenderAction("_SidebarControl", "AdminLTE");}
    </div>
    <!-- ./wrapper -->
    <!-- jQuery 2.2.3 -->
    <script src="/plugins/jQuery/jquery-2.2.3.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
  $.widget.bridge('uibutton', $.ui.button);
    </script>
    <!-- Bootstrap 3.3.6 -->
    <script src="/bootstrap/js/bootstrap.min.js"></script>
    <!-- Morris.js charts -->
    <script src="/plugins/raphael/raphael-min.js"></script>
    <script src="/plugins/morris/morris.min.js"></script>
    <!-- Sparkline -->
    <script src="/plugins/sparkline/jquery.sparkline.min.js"></script>
    <!-- jvectormap -->
    <script src="/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
    <script src="/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
    <!-- jQuery Knob Chart -->
    <script src="/plugins/knob/jquery.knob.js"></script>
    <!-- daterangepicker -->
    <script src="/plugins/moment/moment.min.js"></script>
    <script src="/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- datepicker -->
    <script src="/plugins/datepicker/bootstrap-datepicker.js"></script>
    <script src="/plugins/datepicker/locales/bootstrap-datepicker.zh-CN.js"></script>
    <!-- Bootstrap WYSIHTML5 -->
    <script src="/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
    <!-- Slimscroll -->
    <script src="/plugins/slimScroll/jquery.slimscroll.min.js"></script>
    <!-- FastClick -->
    <script src="/plugins/fastclick/fastclick.js"></script>
    <!-- AdminLTE App -->
    <script src="/dist/js/app.min.js"></script>
    @*<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="/dist/js/pages/dashboard.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="/dist/js/demo.js"></script>*@
    <script src="/plugins/layer/layer.js"></script>
    @RenderSection("Footer",false)
</body>
</html>

TF.WeiXinVote/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title - 微信公众平台 小程序 企业号 开放平台 微信支付 JSSDK Senparc.Weixin SDK</title>
    <meta name="keywords" content="微信SDK,微信公众账号,小程序,SDK,微信公众平台,企业号,服务号,订阅号,微信支付,开放平台,Senparc.Weixin,,Senparc.Weixin.MP,JSSDK,开发者,第三方工具,说明,文档,AppStore,微微嗨,盛派网络,Senparc,.net,c#,小程序开发" />
    <meta name="description" content="Senparc.Weixin SDK，是目前使用率最高的微信C# SDK，包含完整的公众账号、小程序、企业号、开放平台API，帮助第三方开发者轻松实现微信公众账号和企业号开发。目前包含了Senparc.Weixin.MP（微信公众号SDK）、Senparc.Weixin.QY（微信企业号SDK）、Senparc.Weixin.Open（微信开放平台SDK），以及微信支付、微信JSSDK的完整SDK和案例。" />
    <link href="~/Content/darktooltip.min.css" rel="stylesheet" />
    <script src="~/Resource/js/jquery.min.js"></script>
    <script src="~/Content/danktooltip/js/jquery.darktooltip.min.js"></script>
    <script src="https://cdn.bootcss.com/jquery.form/4.2.1/jquery.form.js"></script>
            @RenderSection("HeaderContent", false)</head>
<body>
    <div class="content">
        <div class="senparc-header">
            <div class="wrapper">
                <div class="logo">
                    <a href="http://www.senparc.com">
                        <img src="/images/v2/logo .png" alt="微信SDK" />
                    </a>
                </div>
                <div class="header-title">
                    <a href="@Url.Action("Index", "Home")" title="微信SDK（公众平台/小程序/企业号/开放平/微信支付/JSSDK/摇一摇周边）">微信SDK（公众平台/小程序/企业号/开放平台/微信支付/JSSDK/摇一摇周边）</a>
                </div>
                <div class="navbar-collapse">
                    <ul class="nav-catalog">
                        <li><a href="@Url.Action("Index", "Home")">首页</a></li>
                        <li><a href="@Url.Action("Index", "Menu")">菜单</a></li>
                        <li><a href="@Url.Action("Index", "SimulateTool")">消息模拟</a></li>
                        <li><a href="@Url.Action("JumpToMpOAuth", "OpenOAuth")">开放平台</a></li>
                        <li><a href="@Url.Action("Test", "Cache")">缓存测试</a></li>
                        <li><a href="http://sdk.weixin.senparc.com@(Url.Action("Index", "Document"))">帮助文档</a></li>
                        <li><a href="http://www.cnblogs.com/szw/archive/2013/05/14/weixin-course-index.html" target="_blank">教程</a></li>
                        <li><a href="https://weixin.senparc.com/QA" target="_blank">问答社区</a></li>
                        <li><a href="https://github.com/JeffreySu/WeixinResource" target="_blank">更多开发资源</a></li>
                    </ul>
                    <div class="clear"></div>
                </div>
                <div class="clear"></div>
            </div>
        </div>
        <div id="noticearea">
            <div class="wrapper">
                @*<span>重要公告（2017-2-22）：Nuget 上的 Senparc.Weixin.MP.dll v14.3.126 有一个统一订单的 bug，已经在 <a href="https://www.nuget.org/packages/Senparc.Weixin.MP/14.3.127" target="_blank">v14.3.127</a> 中修正。</span>*@
                <span>2017年3月4日 17:00 - 3月5日 23:00 在线Demo将进行升级调试，期间可能造成访问不稳定，请谅解！</span>
            </div>
        </div>
        <div class="senparc-jumbotron">
            <div class="wrapper">
                <div class="container-left">
                    <ul>
                        <li><a href="https://weixin.senparc.com">Senparc.Weixin SDK 官网</a></li>
                        <li><a href="https://github.com/JeffreySu/WeiXinMPSDK" target="_blank">源代码及示例下载</a></li>
                        <li><a href="https://weixin.senparc.com/QA" target="_blank">微信技术交流社区</a></li>
                        <li><a href="http://www.cnblogs.com/szw/archive/2013/01/13/senparc-weixin-mp-sdk.html" target="_blank">更多使用说明</a></li>
                        <li><a href="https://www.nuget.org/packages/Senparc.Weixin.MP" target="_blank">Nuget项目</a></li>
                        <li><a href="http://sdk.weixin.senparc.com@(Url.Action("Index", "Document"))">下载帮助文档</a></li>
                        <li><a href="http://www.cnblogs.com/szw/archive/2013/05/14/weixin-course-index.html" target="_blank">系列教程</a></li>
                        <li><a href="https://github.com/JeffreySu/WeixinResource" target="_blank">微信开发资源汇总</a></li>
                    </ul>
                </div>
                <div class="container-right">
                    <span class="container-span container-span-title">微信公众平台SDK</span>
                    <span class="container-span">
                        @*全面支持：<br />
                            微信公众号、小程序、微信支付、企业号、开放平台*@
                        <span>全面支持：</span>
                        <span>微信公众号、小程序、微信支付、企业号、开放平台</span>
                    </span>
                    @*<span class="container-span">公众号+微信支付 SDK：Senparc.Weixin.MP.dll</span>
                        <span class="container-span">企业号 SDK：Senparc.Weixin.QY.dll</span>
                        <span class="container-span">开放平台 SDK：Senparc.Weixin.Open.dll</span>*@
                    @*<span class="container-p">公众号+微信支付 SDK：Senparc.Weixin.MP.dll</span>
                        <span class="container-p">企业号 SDK：Senparc.Weixin.QY.dll</span>
                        <span class="container-p">开放平台 SDK：Senparc.Weixin.Open.dll</span>*@
                    <span class="container-p">使用 Senparc.Weixin SDK 轻松打造微信各平台的扩展应用。</span>
                    <div class="contact">
                        <div class="contatc-name">400客服热线：400-9939-858</div>
                        <div class="clear"></div>
                        <div id="qqGroups">QQ群载入中……</div>
                        <div class="clear"></div>
                    </div>
                </div>
                <div class="clear"></div>
            </div>
        </div>
        @if (!IsSectionDefined("catalog"))
        {
            <div class="catalog">
                <a href="@Url.Action("Index", "Menu")">自定义菜单设置工具</a>
                <a href="@Url.Action("Index", "SimulateTool")">消息模拟工具</a>
                <a href="@Url.Action("Test", "Cache")">缓存测试</a>
                <a href="@Url.Action("Index", "AsyncMethods")">异步方法</a>
                <a href="http://sdk.weixin.senparc.com@(Url.Action("Index", "Document"))">帮助文档</a>
            </div>
        }
        @RenderBody()
        <div id="donate" class="feedback">
            <div class="wrapper">
                <div class="feedback-info feedback-info-bs">
                    <p>如果这个项目对你有用，</p>
                    <p>我们欢迎各方任何形式的捐助，</p>
                    <p>也包括参与到项目代码更新或意见反馈中来。</p>
                    <p>谢谢！</p>
                </div>
                <div class="feedback-action">
                    <img src="/images/v2/ewm_03.png" />
                    <p>资金捐助（支付宝钱包扫一扫）</p>
                </div>
            </div>
            <div class="segregate"></div>
            <div class="wrapper">
                <div class="feedback-info">
                    <p>《微信公众平台快速开发》图书众筹</p>
                    <div class="crowdfunding-note">
                        <p class="crowdfunding-note">
                            &nbsp; &nbsp;  &nbsp; 为了将我们积累的经验更多、更系统地与开发者分享，我们已和电子工业出版社签订了约稿协议，书名为《微信公众平台快速开发》（暂定）。全书内容从案例出发，涵盖从微信的基础接口介绍、Senparc.Weixin.MP（微信公众平台SDK）的深入剖析，以及我们在研究过程中发现的许多微信开发“坑”，都一一向读者介绍。<br />
                            &nbsp; &nbsp;  &nbsp; 这是一本饱含诚意的书，由Senparc.Weixin作者苏震巍及核心团队倾情编写，为的是向开发者们分享最原汁原味的Senparc.Weixin架构及微信开发的精髓。<br />
                            &nbsp; &nbsp;  &nbsp; 感谢您对Senparc的支持！<br />
                        </p>
                    </div>
                </div>
                <div class="feedback-action">
                    <img src="/images/crowdfunding-qrcode.png" />
                    <p>参与众筹（微信扫一扫）</p>
                </div>
            </div>
        </div>
        <div class="footer">
            <p class="footer-contact">
                新浪微博：
                <a href="http://weibo.com/jeffreysu1984" target="_blank">@@苏震巍</a>
                @*QQ:<a href="javascript:;">498977166</a>*@
            </p>
            <p class="footer-icon">&copy; 2006-@DateTime.Now.Year Senparc，苏州盛派网络科技有限公司，版权所有，保留所有权利。</p>
        </div>
        @RenderSection("scripts", required: false)
        <div style="display: none;">
            <script>
                var _hmt = _hmt || [];
                (function () {
                    var hm = document.createElement("script");
                    hm.src = "//hm.baidu.com/hm.js?a8ad9ff7b9dd4cbb5510f6a929ba085f";
                    var s = document.getElementsByTagName("script")[0];
                    s.parentNode.insertBefore(hm, s);
                })();

                $(function () {
                    loadQQGroups();
                });

                function loadQQGroups() {
                    $.ajax({
                        type: "get",
                        async: false,
                        url: "https://weixin.senparc.com/WeixinSdk/GetSdkQqGroupListJson",
                        dataType: "jsonp",
                        jsonp: "callbackparam", //服务端用于接收callback调用的function名的参数
                        jsonpCallback: "success_jsonpCallback", //callback的function名称
                        success: function (json) {
                            $('#qqGroups').html(json[0].html);
                            $('#contact-content li.contact-qq').darkTooltip({
                                theme: 'light'
                            });
                        },
                        error: function () {
                            //alert('fail');
                        }
                    });
                }
            </script>
        </div>
    </div>
</body>
</html>

TF.WeiXinVote/Views/Shared/_Pagination.cshtml
@model TF.PageModel
@{
    var url = Model.Url;
    var currentpage = Model.CurrentPage;
    var totalpage = Model.TotalPage;

    var minpage = Math.Max(1, currentpage - 3);
    var maxpage = Math.Min(totalpage, minpage + 7);
    minpage = Math.Max(1, maxpage - 7);
}

<ul class="pagination pagination-sm no-margin pull-right">
    <li><a href="@url.Fmt(1)">&laquo;</a></li>
    @for (long i = minpage; i <= maxpage; i++)
    {
        if (i == currentpage)
        {
            <li class=" active"><a href="#" tabindex="0">@i</a></li>
        }
        else
        {
            <li class=" "><a href="@(url.Fmt(i))" tabindex="0">@i</a></li>
        }
    }
    <li><a href="@url.Fmt(totalpage)">&raquo;</a></li>
</ul>